# 1. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [3]:
import numpy as np

In [2]:
# 스칼라
x = 6
x

6

In [3]:
a = np.array([1])
a, a.shape

(array([1]), (1,))

In [4]:
# 벡터
x = np.array([1,2,3])

print("x = ", x)
print("dimension of x is {}".format(x.shape))

x =  [1 2 3]
dimension of x is (3,)


In [5]:
np.argmax(x)

2

In [6]:
# matrix
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))
print("argmax {}".format(np.argmax(y, axis=1)))

array dimension (3, 3)
array size 9
argmax [2 2 2]


In [8]:
x = np.array([[[1, 2, 3], 
               [3, 2, 5]], 
              [[1, 7, 8], 
               [5, 4, 6]]])

x, x.shape

(array([[[1, 2, 3],
         [3, 2, 5]],
 
        [[1, 7, 8],
         [5, 4, 6]]]),
 (2, 2, 3))

## Indexing / Slicing

<img src="axes.png" width="600">

<img src="numpy.png" width="400">



<img src="tensor.jpg" width="600">

## Slicing

<img src="numpy1.png" width="300">

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [11]:
arr[2]

array([7, 8, 9])

In [12]:
arr[2, :]

array([7, 8, 9])

In [13]:
arr[2:, :]

array([[7, 8, 9]])

In [14]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [15]:
arr[1, :2]

array([4, 5])

In [16]:
arr[1:2, :2]

array([[4, 5]])

### 벡터의 내적(inner product) 
- 내적이 되려면 두 벡터의 dimension 이 같아야 한다. 내적은 각 element 의 곱을 모두 더한 것이다.
- inner product 은 dot product (점곱) 이라고도 불린다.

In [17]:
a = np.array([2,5,1]).reshape(-1,1)
print(a)

[[2]
 [5]
 [1]]


In [18]:
b = np.array([4,3,5]).reshape(-1,1)
print(b)

[[4]
 [3]
 [5]]


$\mathbf{a}^T\mathbf{b} = \begin{bmatrix} 2 & 5 & 1\end{bmatrix}\begin{bmatrix}4\\3\\5\end{bmatrix} = \begin{bmatrix}2*4 + 5*3 + 1*5\end{bmatrix} = 28$

In [19]:
# a, b 의 내적 ==> scalar 
np.dot(a.T, b)

array([[28]])

## matrix 곱셈 (행렬 곱셈, dot product)

### 두 행렬 A 와 B 는 A 의 열(column) 갯수가 B 의 행(row) 갯수와 같을 때 곱할 수 있다. 결과 행렬 C 의 shape 은 A 의 row x B 의 column 이 된다.

<img src="matmul2.png" width="250">
<img src="matmul.png" width="250">

$$\mathbf{A} = \begin{bmatrix}2&5&1\\4&5&3\end{bmatrix} \text{ and } \mathbf{B}=\begin{bmatrix}4&3&5&7\\9&5&3&4\\5&3&6&7\end{bmatrix}$$
$$\mathbf{AB} = \begin{bmatrix}2*4+5*9+1*5&2*3+5*5+1*3&2*5+5*3+1*6&2*7+5*4+1*7\\4*4+5*9+3*5&4*3+5*5+3*3&4*5+5*3+3*6&4*7+5*4+3*7\end{bmatrix}$$

In [20]:
a = np.array([[2, 1], [1, 4]])
b = np.array([[1, 2, 0], [0, 1, 2]])
print(a)
print(b)
print()
print(np.matmul(a, b))

[[2 1]
 [1 4]]
[[1 2 0]
 [0 1 2]]

[[2 5 2]
 [1 6 8]]


In [21]:
print(a@b)

[[2 5 2]
 [1 6 8]]


In [22]:
print(a.dot(b))

[[2 5 2]
 [1 6 8]]


### 전치행렬 (Transposed Matrix)

In [23]:
# matrix transpose
A = np.arange(9).reshape((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
print(A.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [25]:
A = np.array(range(10)).reshape((2,5))
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
B = A.T
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [27]:
print(A.shape)
print(B.shape)

(2, 5)
(5, 2)


## random value

np.random.random_sample  :  [0.0, 1.0)  사이의 random 숫자   
> alias : np.random.random   ((n, m))  


np.random.randn : 표준정규분포의 random 숫자

In [4]:
np.random.seed(10)

In [5]:
print(np.random.random_sample((3, 2)))
print()
print(np.random.random((3, 2)))                # alias of random_sample

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]]

[[0.19806286 0.76053071]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]]


In [6]:
np.random.rand(3, 2)                             # same as random.random_sample

array([[0.00394827, 0.51219226],
       [0.81262096, 0.61252607],
       [0.72175532, 0.29187607]])

## np.linspace()

np.linspace(start, end, num)  - [start, end] 를 균일한 간격으로 num 개 element 생성

In [7]:
arr = np.linspace(0, 20, 30)
arr

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

## Boolean Indexing

In [8]:
x = np.array([-2, 0, 4, 6, -8, 5, 9, 2])
x

array([-2,  0,  4,  6, -8,  5,  9,  2])

In [9]:
x < 0

array([ True, False, False, False,  True, False, False, False])

In [10]:
x[x < 0]

array([-2, -8])